remote_theme: andrewbanchich/forty-jekyll-theme

plugins:
  - jekyll-remote-theme

# site settings
title: Portfolio
subtitle: by HTML5 UP
email: michael.patron.30@gmail.com
description: My web Portfolio site.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Montpellier
# state: 
zip_code: 34090
country: France
phone: +33 662799354

# Institut information
institut_description: Located in the Parc Euromédecine, the Montpellier Cancer Research Institute (U1194) is located on the Val d'Aurelle Campus (ICM, Institut régional du Cancer Montpellier / Val d'Aurelle).
support: U1194 Research Centre supported by Inserm, the University of Montpellier and the Montpellier Cancer Institute (ICM)
institut_street_adress: 208 avenue des Apothicaires
city: Montpellier
zip_code: 34298
country: France
ircm_url: https://www.ircm.fr/

# Team information
team_description: 
team_url: https://www.ircm.fr/index.php?pagendx=243

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  ORCID: https://orcid.org/0000-0002-5713-5219
  GitHub: https://github.com/patron-michael 
  GitLab: https://gitlab.com/patron-michael
#  Google-Plus: 
#  Instagram:
#  LinkedIn: 
#  Twitter: 
#  Facebook:
#  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
